import {
  AMETHYST_TIDE,
  DESERT_SUN,
  EMBER_STORM,
  GILDED_HAZE,
  GLACIER_STEEL,
  INNER_FIRE,
  MOONLIT_LANTERNS,
  MOSSY_BACKLIGHT,
  OIL_SLICK,
  SYNTH_NEON,
  WARM_IVORY,
  WET_JADE,
} from "./looks";
import {
  AMAZING_SPIRE,
  BICOMPLEX_DRIFT,
  BLOOM_BULB,
  BUBBLE_ORB,
  CAVERN_PORES,
  CITADEL_RAMPARTS,
  CORAL_BLOOM,
  CROSS_VAULT,
  DIAMOND_LATTICE,
  FOAM_ORB,
  KLEINIAN_SANCTUM,
  REEF_SPIRES,
  SPONGE_BALL,
  TETRA_GASKET,
  THORN_RELIQUARY,
  WISP_BLOOM,
} from "./shapes";
import type { FractalPreset, FractalShape, Look } from "./types";

/**
 * Curated presets (ADR-0007, recast by ADR-0010): each is now a named shape × look
 * pairing instead of a monolithic snapshot. The pairings reproduce the original
 * M2/M5 images exactly; the halves live in `shapes.ts` and `looks.ts`.
 */

const pair = (
  id: string,
  name: string,
  description: string,
  shape: FractalShape,
  look: Look,
): FractalPreset => ({ id, name, description, shape, look });

export const PRESETS: readonly FractalPreset[] = [
  pair(
    "sunstone-reliquary",
    "Sunstone Reliquary",
    "Thorned kaleidoscopic spires in low raking desert sun, sandstone tones.",
    THORN_RELIQUARY,
    DESERT_SUN,
  ),
  pair(
    "crystal-reef",
    "Crystal Reef",
    "Purple/cyan recursive crystals with shallow focus.",
    REEF_SPIRES,
    AMETHYST_TIDE,
  ),
  pair(
    "amethyst-sanctum",
    "Amethyst Sanctum",
    "Pseudo-Kleinian vaults in glossy purple/cyan crystal, lit from the nave.",
    KLEINIAN_SANCTUM,
    AMETHYST_TIDE,
  ),
  pair(
    "ivory-cross-vault",
    "Ivory Cross Vault",
    "Twisted cross-channel Menger lattice in soft ivory light.",
    CROSS_VAULT,
    WARM_IVORY,
  ),
  pair(
    "moss-coral",
    "Moss Coral",
    "Smooth-union coral fused from nested spheres, under soft mossy backlight.",
    CORAL_BLOOM,
    MOSSY_BACKLIGHT,
  ),
  pair(
    "steel-reef",
    "Steel Reef",
    "Recursive mandelbox crystals in cold near-monochrome steel.",
    REEF_SPIRES,
    GLACIER_STEEL,
  ),
  pair(
    "amethyst-bubble-orb",
    "Amethyst Bubble Orb",
    "A sphere of packed Apollonian bubbles in glossy purple/cyan crystal.",
    BUBBLE_ORB,
    AMETHYST_TIDE,
  ),
  pair(
    "sunlit-citadel",
    "Sunlit Citadel",
    "Low Preetham sun raking warm light across sandstone ramparts.",
    CITADEL_RAMPARTS,
    DESERT_SUN,
  ),
  pair(
    "lantern-grotto",
    "Lantern Grotto",
    "Moonless night in an apollonian cavern; warm lantern pores carry the light.",
    CAVERN_PORES,
    MOONLIT_LANTERNS,
  ),
  pair(
    "ivory-sponge-ball",
    "Ivory Sponge Ball",
    "A ball drilled through with Menger holes, in soft warm ivory light.",
    SPONGE_BALL,
    WARM_IVORY,
  ),
  pair(
    "jade-gasket",
    "Jade Gasket",
    "Sharp Sierpinski tetrahedron in wet glossy jade.",
    TETRA_GASKET,
    WET_JADE,
  ),
  pair(
    "amethyst-diamond",
    "Amethyst Diamond",
    "Octahedral diamond lattice in glossy purple/cyan crystal.",
    DIAMOND_LATTICE,
    AMETHYST_TIDE,
  ),
  pair(
    "neon-drift",
    "Neon Drift",
    "Exotic hypercomplex Julia set in electric magenta-to-cyan neon.",
    BICOMPLEX_DRIFT,
    SYNTH_NEON,
  ),
  pair(
    "ember-reliquary",
    "Ember Reliquary",
    "Molten thorned kaleidoscopic spires glowing with crystalline inner fire.",
    THORN_RELIQUARY,
    INNER_FIRE,
  ),
  pair(
    "gilded-spire",
    "Gilded Spire",
    "Rotated Amazing Box spires in warm gilded haze.",
    AMAZING_SPIRE,
    GILDED_HAZE,
  ),
  pair(
    "ember-drift",
    "Ember Drift",
    "Exotic hypercomplex Julia set adrift in stormy ember light.",
    BICOMPLEX_DRIFT,
    EMBER_STORM,
  ),
  pair(
    "lantern-wisps",
    "Lantern Wisps",
    "Sinusoidal bulb tendrils glowing from warm lantern light in the dark.",
    WISP_BLOOM,
    MOONLIT_LANTERNS,
  ),
  pair(
    "verdant-bloom",
    "Verdant Bloom",
    "Bright wet-glossy mandelbulb in cold turquoise jade.",
    BLOOM_BULB,
    WET_JADE,
  ),
  pair(
    "moss-foam-orb",
    "Moss Foam Orb",
    "A backlit sphere of nested Kleinian chambers in olive green.",
    FOAM_ORB,
    MOSSY_BACKLIGHT,
  ),
  pair(
    "oil-bloom",
    "Oil Bloom",
    "A glossy mandelbulb with a thin-film rainbow oil-slick sheen.",
    BLOOM_BULB,
    OIL_SLICK,
  ),
];
